version: '1'
services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/app

networks:
  network:
    driver: bridge

volumes:
  yomankum:
    external: true