spring:
  datasource:
    url: jdbc:mysql://localhost:8080/yomankum?useSSL=false&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: yomankum
    password: ENC(7pOexY0QSqvvvuQsG1IrCQ==)
  jpa:
    database: mysql

    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create
    show-sql: true
    properties:
      format_sql: true

  security:
    oauth2:
      client:
        registration:
          google: # 도메인 없어서 불가
            client-id: cliendtId
            client-secret: cliendtSecret
            scope:
              - email
            redirect-uri: http://localhost:8080/
          naver:
            client-id: ENC(1TUWMIpVqsoShIWIpjuHA/LIkm5Ay3k/C6a+e8Wyp7A=)
            client-secret: ENC(bDHKNCUwjZckHX4jS0GsQfaOJataVzF0)
            scope:
              - name
              - email
              - mobile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/
          kakao:
            client-id: ENC(XtiC/Bfjixhya2hoePFMmIBQWJmdS05pl54THC4/uRSTpzcTMyi0VB32+uFB1nVy)
            client-secret: ENC(y1mcMVCslc3GJl/zEeTZ5bAVMmQIynG+fBl+TOQK9/I4/MxJT+ivZScCzkTpaL3G)
            scope:
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/
            client-authentication-method: POST
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 로그인 GET 요청 URL
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰 발급 URL
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWithMD5AndDES
    ivGeneratorClassname: org.jasypt.iv.NoIvGenerator

token:
  keys:
    kakao: # https://kauth.kakao.com/.well-known/jwks.json
      e:
        first: AQAB
        second: AQAB
      n:
        first: q8zZ0b_MNaLd6Ny8wd4cjFomilLfFIZcmhNSc1ttx_oQdJJZt5CDHB8WWwPGBUDUyY8AmfglS9Y1qA0_fxxs-ZUWdt45jSbUxghKNYgEwSutfM5sROh3srm5TiLW4YfOvKytGW1r9TQEdLe98ork8-rNRYPybRI3SKoqpci1m1QOcvUg4xEYRvbZIWku24DNMSeheytKUz6Ni4kKOVkzfGN11rUj1IrlRR-LNA9V9ZYmeoywy3k066rD5TaZHor5bM5gIzt1B4FmUuFITpXKGQZS5Hn_Ck8Bgc8kLWGAU8TzmOzLeROosqKE0eZJ4ESLMImTb2XSEZuN1wFyL0VtJw
        second: qGWf6RVzV2pM8YqJ6by5exoixIlTvdXDfYj2v7E6xkoYmesAjp_1IYL7rzhpUYqIkWX0P4wOwAsg-Ud8PcMHggfwUNPOcqgSk1hAIHr63zSlG8xatQb17q9LrWny2HWkUVEU30PxxHsLcuzmfhbRx8kOrNfJEirIuqSyWF_OBHeEgBgYjydd_c8vPo7IiH-pijZn4ZouPsEg7wtdIX3-0ZcXXDbFkaDaqClfqmVCLNBhg3DKYDQOoyWXrpFKUXUFuk2FTCqWaQJ0GniO4p_ppkYIf4zhlwUYfXZEhm8cBo6H2EgukntDbTgnoha8kNunTPekxWTDhE5wGAt6YpT4Yw
      use:
        first: sig
        second: sig
      alg:
        first: RS256
        second: RS256
      kty:
        first: RSA
        second: RSA
      kid:
        first: 3f96980381e451efad0d2ddd30e3d3
        second: 9f252dadd5f233f93d2fa528d12fea
    google:
      e:
        first: first
        second: second
      n:
        first: first
        second: second
      use:
        first: first
        second: second
      alg:
        first: first
        second: second
      kty:
        first: kty
        second: second
      kid:
        first: first
        second: second
  valid:
    time: ENC(vQYPnJrSLvHrnD2j/dZ83w==)
  refresh:
    valid:
      time: ENC(8U+v/B6+HM/9LEJQNE08bQ==) # 30일
  secret:
    key: ENC(BMicTjYyhaqYR52nqX/xH0My/7rlkWlcdwCBUZMp9Xm7wDywILk2GbmzWni5kGbLSNLYtjmoWqc7lAZLeFqtcMWuMF4vC4BPxDq2Qtg9HXy5ge+5RI1nK6Z6cjwLJXQUuNHUt+WEM+XJu/a3EMOYe7KNcLTWmyiTYamSKNe1iNMIQs0GBIj0GYK4vDksRLYjQmuH9DnqfFs8d6QcWPXEDXaR4YcJBdFmIxf8uiX5r+1clmu+82FU6mdkTNqm5U3H601Yql3aph3DLl0EswUGzmgmbOq0xGzh6pBRCFXysxMatJFsK6uLbrlB22rjkZljyBx7/+5f9XIm7mj1dG8PA6gOOFHZA5+GBAMwaL8iUB1ylThtAGQi3fdd23JIB2iQ2g22p/hoVK/avUuHdCqZ6BJ/5E87rzquHGOAHpGU47xx6qr+ADPRAPip04fmmB/0nwi6jjw0iEc/2kLp7Q83wELbc23wJJbJbtzptIp2FY8WGpUuF+V4ow==)
