oauth:
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_CLIENT_ID}
    scope:
      - profile
      - email
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    client_secret: ${KAKAO_CLIENT_SECRET}
    redirect_uri: http://localhost:5173/oauth2/redirect
    authorization_grant_type: authorization_code
    client_authentication_method: client_secret_post
    scope:
      - account_email
  naver:
    client_id: ${NAVER_CLIENT_ID}
    client_secret: ${NAVER_CLIENT_ID}
    redirect_uri: http://localhost:5173/oauth/redirect/naver
    authorization_grant_type: authorization_code
    client_authentication_method: client_secret_basic
    scope:
      - name
      - email
      - mobile
    client_name: Naver
  provider:
    google:
      authorization_uri: https://kauth.google.com/oauth/authorize
      token_uri: https://kauth.google.com/oauth/token
      user_info_uri: https://kapi.google.com/v2/user/me
      user_name_attribute: id
    kakao:
      authorization_uri: https://kauth.kakao.com/oauth/authorize
      token_uri: https://kauth.kakao.com/oauth/token
      user_info_uri: https://kapi.kakao.com/v2/user/me
      user_name_attribute: id
    naver:
      authorization_uri: https://nid.naver.com/oauth2.0/authorize
      token_uri: https://nid.naver.com/oauth2.0/token
      user_info_uri: https://openapi.naver.com/v1/nid/me
      user_name_attribute: response
