spring:
  datasource:
    url: ${DATA_URL}
    username: ${DATA_USERNAME}
    password: ${DATA_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

token:
  valid:
    time: 3600000
  refresh:
    valid:
      time: 86400000
  secret:
    key: ${SECRET_KEY}

mail:
  id: ${MAIL_ID}
  template:
    signup: email/joinMailForm
    password: email/passwordResetMailForm
  title:
    signup: YOMANKUM * 가입 코드 전송
    password: YOMANKUM * 비밀번호 재설정

springdoc:
  packages-to-scan: com.account.yomankum
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /yomankum/api-docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method

commit:
  final:
    number: 68
    datetime: 2024-03-19 23:47

auth:
  code:
    duration:
      signup: 900
      password: 900
